// An Account Generator Bot.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// (c) Reeshuxd 2021


const { Telegraf, Markup } = require('telegraf')
const AccGen = new Telegraf("1878988670:AAHvZBDXdYnO89MoYme3y5HaIRQJHP_HSiQ")
const { os } = require('os')


// Replace these accounts with your accounts
const accounts = [
        "somemail@mail.com:Password:",
        "somemail@mail.com:Password:",
        "somemail@mail.com:Password:",
        "somemail@mail.com:Password:",                   
	"somemail@mail.com:Password:"
];

AccGen.command('start', async (ctx) => {
	const text = `
Heya ${ctx.message.from.first_name}

It's a AccGenBot made with JavaScript!
Click The Below Button For More Help!
`
	await ctx.reply(
		text,
		Markup.inlineKeyboard([
			[Markup.button.callback("Help And Commands", "help")],
			[Markup.button.url("My Source Code", "https://github.com/Reeshuxd/AccGenBot")]
		    ]
	      ),
	)
})

AccGen.action('help', async (ctx) => {
	const text = `
<b>AccGenBot Help-menu:</b>

- /start: <b>To Start Me.</b>
- /gen: <b>To Genete a Account.</b>

<b>Thanks for using me!</b>
	`
	await ctx.answerCbQuery()
        await ctx.editMessageText(
		text,
		{parse_mode: "HTML"}
	)
})
AccGen.command('gen', async (ctx) => {
	if (ctx.chat.type != "private") { 
		await ctx.reply('Generate Accounts in my PM!')
		return
	}
	const Acc_name = process.env.ACC_NAME
	const account = accounts[Math.floor(Math.random() * accounts.length)]
        const acc = account.split(":")
        const email = acc[0]
        const pass = acc[1]
	Temxt = `
<b>Generated ${Acc_name} Account:</b>

<b>Email:</b> <code>${email}</code>
<b>Password:</b> <code>${pass}</code>
<b>Generated By:</b> <code>${ctx.message.from.id}</code>

<b>Thanks For Using Me!</b>
	`
	const channel = process.env.CHANNEL_ID
	const c_uname = process.env.CHANNEL_US
	const check = await AccGen.telegram.getChatMember(
		channel,
		ctx.message.from.id
	)
	if (check.status == "member" || check.status == "administrator" || check.status == "creator") {
		await ctx.reply(Temxt, {parse_mode: "HTML"})
		return
	}
	else {
		ctx.reply(
			"Join My Channel To Use Me!",
			Markup.inlineKeyboard([
				[Markup.button.url('Join My Channel', `${c_uname}`)]
			    ]   
			)
		)

		return
        }

})


AccGen.launch()
console.log('Succesfully Started Bot!')
console.log('Visit @TheTeleGramSupportChat!')
